version: '3.3'
services:
  database:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Qwertyu7!"
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./Blob/:/opt/azurite/folder

  web-api:
    environment:
#      - PASSWORD_ENV_SEEDED="some.long.password" #this password uses for HTTPS certificate generation inside image
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./Server
      dockerfile: ./src/WebApiDockerfile
#      args:
#        - PASSWORD_ENV_SEEDED=${PASSWORD_ENV_SEEDED}
    image: ticket-manager/web-api
    ports:
      - "8080:80"
      - "7116:443"
    depends_on:
      - database
      - auth
        
  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: ./Server
      dockerfile: ./src/AuthDockerfile
#      args:
#        - PASSWORD_ENV_SEEDED=${PASSWORD_ENV_SEEDED}
    image: ticket-manager/auth
    ports:
      - "8081:80"
      - "7058:443"
    depends_on:
      - database

  web:
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    image: ticket-manager/web
    ports:
      - "80:80"
    depends_on:
      - web-api


volumes:
  data:
