version: '3.4'
services:
  database:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Qwertyu7!"
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
    healthcheck:
      test:  /opt/mssql-tools/bin/sqlcmd -U sa -P Qwertyu7! -Q 'select 1' -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./Blob/:/opt/azurite/folder

  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./Server
      dockerfile: ./src/WebApiDockerfile
    image: ticket-manager/web-api
    ports:
      - "8080:80"
      - "7116:443"
    depends_on:
      auth:
        condition: service_started 
      database:
        condition: service_healthy

  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./Server
      dockerfile: ./src/AuthDockerfile
    image: ticket-manager/auth
    ports:
      - "8081:80"
      - "7058:443"
    depends_on:
      database:
        condition: service_healthy

  web:
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    image: ticket-manager/web
    ports:
      - "8082:80"
    depends_on:
      - web-api

volumes:
  data:
