namespace Core;

public enum ErrorCodes
{
  LOGIN_FAILED,
  EMAIL_IS_TAKEN,
  ADD_COMMENT_ACCESS_DENIED,
  USER_NOT_FOUND_BY_CLAIMS_ERROR,
  PARSE_USER_ID_FROM_CLAIMS_ERROR,
  DELETE_TICKET_ACCESS_DENIED,
  GET_TICKET_ACCESS_DENIED,
  GET_ALL_TICKETS_ACCESS_DENIED
}
